CXXFLAGS += -Wall
# CXXFLAGS += -std=c++11

maina:	maina.cpp
	g++ $(CXXFLAGS) maina.cpp -o maina

mainb:	mainb.cpp
	g++ $(CXXFLAGS) mainb.cpp -o mainb

mainc:	mainc.cpp
	g++ $(CXXFLAGS) mainc.cpp -o mainc

clean:
	rm -f maina mainb mainc
